### PR TITLE
Use exception_ptr in translation exceptions

### PR DESCRIPTION
**Pull request by fealebenpae**
Our current rethrowing pattern seems not to work with Windows SEH - the rethrown exception points to garbage memory. Explicit use of std::exception_ptr works, though.

### CODE REVIEW

**Comment by tgoyne** [comment]
SEH is unrelated to c++ exceptions.

**Comment by fealebenpae** [comment]
Yes, you're right - I've read up on the differences between `try/catch` and `__try/__except` and I understand this better now.

I guess it must be a MSVC bug then - the exact same code works great in the .NET SDK compiled with MSVC 2017, but produces weird results at runtime in the JS SDK where it's compiled with MSVC 2015.

**Comment by tgoyne** [comment]
I highly doubt that it is a MSVC bug, especially since I have used `throw;` without problems with MSVC many times in the past. I suspect there are configuration problems such as mismatched compiler settings.

**Comment by bdash** [comment]
And if this _is_ in fact a compiler bug, is this really the only use of `throw;` that's problematic? There are a number of other uses in core and object store.

**Comment by fealebenpae** [comment]
That's entirely possible. Would you be willing to look at the `cl.exe` invocation to see if anything there seems wrong, @tgoyne?

@bdash, .NET compiles with MSVC 2017, and so does Core. The Windows tests for Object Store are built with MSVC 2017, too. It's only Node.js that needs 2015, but as @tgoyne suggested it's probably an error in the gyp changes I made in realm-js rather than a bug. The JS SDK being the only one that uses MSVC 2015 threw me off.

**Comment by fealebenpae** [comment]
I managed to fix this by defining `_HAS_EXCEPTIONS=1`. I'm not at all sure what the actual problem was, or how this fixes it. I'm going to chalk it up to gyp being wonderful.

Thank you for pointing me in the right direction, @tgoyne.

**Comment by tgoyne** [comment]
The build settings are probably missing `/EHsc` since I think that's what defines `_HAS_EXCEPTIONS=1`.

**Comment by fealebenpae** [comment]
We have `/EHsc` - I had to enable it manually in gyp. Without it MSVC complained every time it encountered a try/catch construct.

**Pull request closed without merging**
