### PR TITLE
Misc cleanup

### PR DESCRIPTION
**Pull request by ironage**
Improve some tests, remove some dead code and "FIXME" comments.

### CODE REVIEW

**Comment by tgoyne** [comment]
realm-js still uses EventLoopDispatcher.

**Comment by ironage** [comment]
I undid the change to remove the EventLoopDispatcher, I wasn't aware anyone was using it thanks.

**Comment by fealebenpae** [comment]
@ironage great work on `std::apply`! I'm so glad to see that todo finally resolved.

**Comment by ironage** [comment]
Bump for reviews 😄

**Pull request merged**
