### PR TITLE
workaround VS ternary expression compilation bug

### PR DESCRIPTION
**Pull request by AndyDentFree**
@bdash, @kristiandupont or @fealebenpae  please review.
I think the problem lies in the handling of ternary expressions - I was unable to get any variation on them to compile for this `StringData` creation.

### CODE REVIEW

**Comment by tgoyne** [comment]
`op.property ? StringData{op.property->name} : ""` works on the [online compiler](http://webcompiler.cloudapp.net/) but I don't know if that's the same compiler version.

**Comment by AndyDentFree** [comment]
As I said in the original issue description, I think the problem was partly due to matching up `std::string` vs `template<class T, class A> StringData(const std::basic_string<char, T, A>&);` because I couldn't get the ternary expression to work without the error message.

As a general comment, VS in its various incarnations over the last N years has **always** been the most _creative_ in the way it interpreted which overloads to use, out of a very wide range of compilers I have built with. It is vastly better nowadays but this little problem was almost pleasurably nostalgia-inducing.
(and a little nausea-inducing)

**Comment by kristiandupont** [comment]
:+1:

**Comment by bdash** [comment]
@AndyDentFree, this would have been a candidate for squashing your changes when merging or rebasing to clean up the commit history, as the intermediate state commits are just noise.

**Pull request merged**
