### PR TITLE
Pull over sync changes

### PR DESCRIPTION
**Pull request by alazier**
@fealebenpae

### CODE REVIEW

**Comment by fealebenpae** [comment]
Looking at the `al-js-sync` branch it doesn't look like it actually contains any sync changes that would be included in its tip. What's more, GitHub says this PR is basically change-neutral.

I'm curious about https://github.com/realm/realm-object-store/commit/158a45a7a50ff2273c70e75d84d15a6a9d51402b, though - it says I'm the author but you pushed it and I have no recollection of authoring such a commit. Did you `git commit --author`? Also, that one commit looks like it undoes all the sync changes in Object Store, why would it be there?

**Comment by fealebenpae** [comment]
Also, probably someone more familiar with sync in Object Store should take a look at this PR.

**Comment by alazier** [comment]
@fealebenpae not sure what is going on with the changes in this pr. Just made this because it is what you had been asking for. Perhaps I messed up when I was pushing across remote.

**Comment by alazier** [comment]
This does seem a bit wrong though...

**Comment by alazier** [comment]
Ok think i fixed it...

**Comment by fealebenpae** [comment]
Yep, this looks better. 👍 FWIW

**Pull request merged**
