### PR TITLE
copy_realm_to_recovery should take path as param

### PR DESCRIPTION
**Pull request by beeender**
The full path has been saved in the file_actions,
copy_realm_file_to_recovery_directory doesn't have to append the name to
the recovery path -- it will cause a File::NotFound thrown always.

### CODE REVIEW

**Comment by beeender** [comment]
@austinzheng I am not familiar with those code, not sure how to build a test case to cover it.

**Comment by nhachicha** [comment]
without this fix the client reset feature will not copy the Realm file. it will fail silently with `File::NotFound`, this is not caught by the existing unit test. 

cc @jpsim you may want to  do another cocoa release, once this is merged

**Comment by austinzheng** [comment]
I thought I wrote a test for this, but it looks like I didn't. I can either write a follow-up test, or you can write a test by looking at `file.cpp` and `metadata.cpp`.

A good test for this would:
* Create a dummy realm at a location using `create_dummy_realm()`
* Manually create a file action metadata entry to move the file to a destination
* Execute the file action metadata by running `SyncManager::shared().configure_file_system`
* Assert the Realm file now exists at the path in the test file action metadata entry.

**Comment by nhachicha** [comment]
add unit test here https://github.com/realm/realm-object-store/pull/346

**Comment by austinzheng** [comment]
I prefer to fix this a different way.

**Pull request closed without merging**
