### PR TITLE
add unit test to cover the use of recovery_directory_path, for client…

### PR DESCRIPTION
**Pull request by nhachicha**
Adding unit test for https://github.com/realm/realm-object-store/pull/343

### CODE REVIEW

**Comment by austinzheng** [comment]
Some of the existing tests are failing. Can you either update them if they're wrong, or change the fix if they're correct? Let me know if you have any questions about what they test; they should be self-explanatory.

**Comment by bdash** [comment]
Why is this not just added as part of #343?

**Comment by austinzheng** [comment]
I'm going to fix the tests, squash this PR onto Mulong's PR, and manually commit it once I've verified it.

**Comment by austinzheng** [comment]
On second thought, I want to fix this a different way.

**Pull request closed without merging**
