### PR TITLE
update shared_realm.cpp for new SharedGroupOptions

### PR DESCRIPTION
**Pull request by jpsim**
/cc @bdash

### CODE REVIEW

**Comment by tgoyne** [comment]
SharedGroupOptions is also on core master, so checking for >= 2 is wrong. The lack of any useful versioning for the releases from next-major is pretty awkward too since this won't compile with the most recent release and you can't check that...

**Comment by bdash** [comment]
As a temporary measure, we could do something cheeky like key off the presence of the header guard macro for the new header that `SharedGroupOptions` is declared in.

**Comment by jpsim** [comment]
> As a temporary measure, we could do something cheeky like key off the presence of the header guard macro for the new header that `SharedGroupOptions` is declared in.

Good idea, I'll give that a shot.

**Comment by jpsim** [comment]
I updated this to only use sg options if `REALM_GROUP_SHARED_OPTIONS_HPP` is defined. /cc @bdash @fealebenpae

**Comment by bdash** [comment]
@jpsim, it looks like you neglected to fix the same issue in the tests.

**Comment by jpsim** [comment]
Sorry about that. Thanks @austinzheng for fixing.

**Pull request merged**
