### PR TITLE
Merge latest master into JS

### PR DESCRIPTION
**Pull request by alazier**
@kristiandupont @bdash

### CODE REVIEW

**Comment by bdash** [comment]
The title suggests this is merging `master` into `js`, but the PR appears to do the reverse.

**Comment by kristiandupont** [comment]
We definitely want to converge with master as well but we should probably get everyone on board with the threadid issue before we do.

**Comment by radu-tutueanu** [comment]
I changed the base, as we want to merge js-latest to js

**Comment by alazier** [comment]
@bdash @radu-tutueanu does this look good to merge?

**Comment by radu-tutueanu** [comment]
👍 LGTM

**Pull request merged**
