### PR TITLE
Expose List API for adding, inserting, and setting embedded objects

### PR DESCRIPTION
**Pull request by nirinchev**
This just proxies Core's API for SDKs that can't use the Accessor APIs.

### CODE REVIEW

**Review by cmelchior — CHANGES_REQUESTED** [review]
Java could use these methods as well as right now we create a temporary accessor just for this 👏 

The code looks fine from what I can tell, but there seem to be no tests, which would be nice to add?

**Comment by nirinchev** [comment]
Yeah - I can add a test or two. I didn't initially, because it's directly calling the Core API with no extra logic (and I hope those are well tested).

**Comment by nirinchev** [comment]
@cmelchior added some primitive tests, but I'm not super well versed in Object Store semantics, so let me know if it looks too stupid 😅

**Comment by nirinchev** [comment]
Ping @cmelchior 😛

**Review by cmelchior — APPROVED** [review]

**Pull request merged**
