### PR TITLE
Add a schema check for unreachable embedded objects

### PR DESCRIPTION
**Pull request by ironage**
Fixes https://github.com/realm/realm-object-store/issues/925

### CODE REVIEW

**Comment by tgoyne** [comment]
This rejects orphans unconditionally, while we only want to reject orphans which were explicitly added to the schema and not just auto-discovered. Object store doesn't currently have a way to distinguish those, so either it needs a way to or this needs to be something explicitly called on the schema by the SDK when it is applicable.

**Comment by ironage** [comment]
Thanks, @tgoyne. Since I'm not familiar with how SDK's do their automatic schema discovery the simplest thing is to provide a method on Schema to do the check that SDK's can opt-in to calling at the appropriate time. What would be the best output of such a method, a list of the names of orphans, or would a list of `ObjectSchemaValidationException` still be appropriate?

**Comment by tgoyne** [comment]
I think the behavior we want is:

1. If the schema was discovered, simply do not create tables for any orphaned embedded types. Having types in the schema which do not have backing tables is already something we support for the sake of read-only Realms. This is so that merely defining a class and not using it isn't an error, as that'd be pretty annoying during development.
2. If the embedded object type is explicitly included in the schema by the user, throw an exception. 
3. If the table for the orphaned embedded object type already exists, validate that it's compatible with the schema even if the schema was auto-discovered.

Satisfying all three of these probably requires pushing the knowledge about if the schema was auto-discovered down pretty far into the logic. A pre-emptive validator-or-filter function probably couldn't handle both skipping creating tables but still validating that the schema matches the table if it already exists. The most natural thing would probably be another schema mode? Having separate AdditiveWithEmbeddedOrphansAllowed and AdditiveWithEmbeddedOrphansForbidden modes (preferably with better names) modes would fit with the existing design and leave it to the SDK to pick the appropriate one without having to pass around addition bits of state. Hopefully the actual logic to make that work isn't awful...

**Comment by ironage** [comment]
For sure, I can add another schema mode. Perhaps AdditiveExplicit and AdditiveDiscovered so that we can maybe reuse the code paths for some other future schema checks?
Would it be useful to separate out the explicit/discovered state from the schema mode so that it can be combined with all other schema modes and not just additive? I just want to double check the design matches the conceptual model because I don't have any experience with the discoverable schema code. But I have no problem with adding it if that's what we need.

**Comment by tgoyne** [comment]
Orphaned embedded tables are only a problem for the server, so the check is only needed for synchronized Realms and synchronized Realms always use the additive-only schema mode. I think having this as a flag that can be added to any schema mode would just complicate things, but if I'm wrong and it would be simpler then there's nothing wrong with that approach. I mostly wouldn't want a separate bool that has to be passed down through a bunch of layers because that has a habit of turning into three bools and some really convoluted logic.

**Comment by ironage** [comment]
Replaced by https://github.com/realm/realm-core/pull/4306

**Pull request closed without merging**
