### PR TITLE
Remove duplicate files

### PR DESCRIPTION
**Pull request by radu-tutueanu**
@alazier @mrackwitz 
Having these files twice causes confusion.

Right now we are(should be) using the ones in sync, not sure if there is any difference that should go in there.

### CODE REVIEW

**Comment by mrackwitz** [comment]
The files definitely differ.

**Comment by kristiandupont** [comment]
As @mrackwitz says, there are significant variations there. The question is whether anything was using the files outside the sync folder?

**Comment by radu-tutueanu** [comment]
Only by https://github.com/realm/realm-js-private/blob/master/src/sync_logger.hpp#L30 
and it looks like it was by mistake.  Don't know what effects that has had.

**Comment by bdash** [comment]
IMO the best way to confirm that this change is ok is to:
* Verify that any JS tests related to sync still pass with this change.
* Double-check that there were no changes made to the files being removed on the `js` branch that didn't later make it into `master`.

**Comment by radu-tutueanu** [comment]
Thanks. These files have not been used for a while, but I will make upstream PRs to make sure this does not break anything. :)

**Pull request merged**
