### PR TITLE
[WIP] Allow sync file manager to act on “client reset” file actions

### PR DESCRIPTION
**Pull request by austinzheng**
Depends upon https://github.com/realm/realm-object-store/pull/233

I'm hoping for an API to force `sync` to emit a particular error, which would make writing additional tests possible.

Changes:
- `SyncConfig` now has another field for specifying an optional custom on-disk file path
- A 'diverging histories' error now generates a `ClientReset` error kind
- When receiving a 'diverging histories' error, a client reset file action is generated
- `SyncManager` now acts on file reset actions
- Added more tests

### CODE REVIEW

**Comment by austinzheng** [comment]
The only "WIP" aspect of this is figuring out whether `bad_client_file_ident` and `bad_client_version` can indicate client reset. @kspangsege, might you know?

**Comment by morten-krogh** [comment]
@austinzheng 

It is on the website 
https://realm.io/docs/realm-object-server/#backup 
See the section Client Recovery From A Backup

bad_client_file_ident indicates client reset.

bad_client_version does not.

**Comment by austinzheng** [comment]
Excellent! Thank you so much.

**Comment by austinzheng** [comment]
Closed in favor of https://github.com/realm/realm-object-store/pull/320

**Pull request closed without merging**
