### PR TITLE
Pull in remaining changes from JavaScript

### PR DESCRIPTION
**Pull request by bdash**
This brings in the remaining handful of changes from realm-js's copy of the object store code. It'll allow realm-js to pull in object store's master branch directly.

### CODE REVIEW

**Comment by tgoyne** [comment]
I don't understand what exact the thread_id thing is trying to solve. Our instances aren't *actually* tied to the thread in any way, so reusing an instance from a previous thread that happens to have the same ID shouldn't be a problem (and if it was reasonably possible, intentionally reusing instances from dead threads could be useful). Adding a TLS lookup to every call to verify_thread() (i.e. every access of a property) has a pretty significant performance impact.

More superficially, it should be named ThreadID.

**Comment by bdash** [comment]
There's not a lot of information in the original PR to explain why the change was made (realm/realm-js#480). From looking at the realm-js code, I think the problem was related to realm-js's assumption that there's a single JavaScript context per thread. `RealmClass<T>::constructor` stashes the JavaScript context in `Realm::m_binding_context`. If the thread a `Realm` instance belongs to exits and its identifier is reused before the `Realm` instance is deallocated, a new thread calling `RealmClass<T>::constructor` can get back the existing `Realm` instance, and will find that it is associated with a different JavaScript context than it expects.

Changing the definition of thread ID doesn't seem like the right way to fix that issue.

**Comment by bdash** [comment]
My initial thought for addressing the problem would be for realm-js to have the `Realm` instance cache be partitioned by `(thread, JavaScript Context)` rather than only by thread.

**Comment by alazier** [comment]
Why not just use the JSContext? Those are always disposed/recreated between app runs and refreshes.

**Comment by bdash** [comment]
I'm going to file a new issue in realm-js to track revisiting this thread ID stuff, and will drop the relevant commit from this branch. That will allow us to get the remaining changes merged while we work out a better fix than changing the concept of thread ID.

**Comment by alazier** [comment]
Sounds good @bdash - there is already a ticket https://github.com/realm/realm-js/issues/494 to revisit the design for the threadlocal stuff which I was not really happy with to begin with. Could just modify that one.

**Comment by bdash** [comment]
Wrote up realm/realm-js#552.

**Comment by tgoyne** [comment]
👍

**Pull request merged**
