### PR TITLE
Removed unused `toString` function

### PR DESCRIPTION
**Pull request by JadenGeller**
@bdash @tgoyne

### CODE REVIEW

**Comment by tgoyne** [comment]
The toString overload is used to format failure messages for the schema change tests. If it is actually unused then that is a bug that should be fixed.

**Comment by JadenGeller** [comment]
It's causing a build warning for me. Can we remove it and whoever adds those tests can add it back?

**Comment by JadenGeller** [comment]
To be more clear, it's causing a build warning to due a missing function prototype. It only shows a build warning for being unused if I mark it as static. Should we just add the function prototype?

**Comment by bdash** [comment]
#119 fixes this in a way that makes the custom formatting in failure messages work as intended.

**Pull request closed without merging**
